--- hopefully this improves the shit ai pdx gave us ---

NDefines.NAI.AGGRESSIVENESS = 325.0
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 625.0
NDefines.NAI.MISSION_PICK_CHANCE = 10000.0
NDefines.NAI.PS_SHORT_TERM_POOL = 175.0
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 1000.0

NDefines.NAI.DEVELOPMENT_CAP_BASE = 30
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.2
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 13.0

NDefines.NAI.AI_FORT_PER_DEV_RATIO = 36
NDefines.NAI.FORT_ON_BORDER_MULT = 1.79
NDefines.NAI.FORT_NEXT_TO_FORT_MULT = 0.01

NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 10000.0
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 10000.0
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.3
NDefines.NAI.DANGEROUS_OVEREXTENSION_PERCENTAGE = 0.5

NDefines.NAI.CORRUPTION_BUDGET_FRACTION = 10.0
NDefines.NAI.COLONY_BUDGET_FRACTION = 1.0
NDefines.NAI.ARMY_BUDGET_FRACTION = 4.0
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.4
NDefines.NAI.FORT_BUDGET_FRACTION = 0.6

NDefines.NAIEconomy.STATE_MAINTENANCE_FRACTION = 2.0
NDefines.NAIEconomy.BUDGETING_ADJUSTMENT_STEP = 0.11
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 3.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 3.1
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 4.5
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.175
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 2.1
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 4.35
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIZE = 2.2
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 2.1
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 2.2
NDefines.NAIEconomy.FORT_FRACTION_MILITARIZE = 4.0
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 7.0
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 6.0
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 1.0

NDefines.NAI.EDICT_VALUE_THRESHOLD = 9
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 6
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 3

NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MIN_MULT = 1.0
NDefines.NAI.PEACE_TERMS_PROVINCE_OVEREXTENSION_MAX_MULT = 7.0